import type { Worker, Order, PayrollEntry, DashboardMetrics, Alert } from './types'

export const mockWorkers: Worker[] = [
  {
    id: 'worker-1',
    name: 'Alex Chen',
    email: 'alex@example.com',
    workerId: 'W-001',
    status: 'online',
    platform: 'platform_a',
    lastSeen: new Date(Date.now() - 5 * 60000),
    activeOrders: 12,
    totalEarnings: 4520,
    assignedTo: 'Sarah Johnson',
    notes: 'High performance worker',
  },
  {
    id: 'worker-2',
    name: 'Jordan Blake',
    email: 'jordan@example.com',
    workerId: 'W-002',
    status: 'online',
    platform: 'platform_b',
    lastSeen: new Date(Date.now() - 2 * 60000),
    activeOrders: 8,
    totalEarnings: 3210,
    assignedTo: 'Sarah Johnson',
    notes: 'Consistent quality',
  },
  {
    id: 'worker-3',
    name: 'Morgan Lee',
    email: 'morgan@example.com',
    workerId: 'W-003',
    status: 'busy',
    platform: 'platform_c',
    lastSeen: new Date(Date.now() - 1 * 60000),
    activeOrders: 15,
    totalEarnings: 5890,
    assignedTo: 'Mike Williams',
    notes: 'Processing batch operation',
  },
  {
    id: 'worker-4',
    name: 'Casey Rodriguez',
    email: 'casey@example.com',
    workerId: 'W-004',
    status: 'idle',
    platform: 'platform_a',
    lastSeen: new Date(Date.now() - 15 * 60000),
    activeOrders: 0,
    totalEarnings: 2145,
    notes: 'Available for new assignments',
  },
  {
    id: 'worker-5',
    name: 'Taylor Kim',
    email: 'taylor@example.com',
    workerId: 'W-005',
    status: 'offline',
    platform: 'platform_b',
    lastSeen: new Date(Date.now() - 3 * 3600000),
    activeOrders: 0,
    totalEarnings: 1890,
    notes: 'Offline since morning',
  },
  {
    id: 'worker-6',
    name: 'Devon Park',
    email: 'devon@example.com',
    workerId: 'W-006',
    status: 'online',
    platform: 'platform_c',
    lastSeen: new Date(Date.now() - 30000),
    activeOrders: 6,
    totalEarnings: 3450,
    assignedTo: 'Mike Williams',
  },
]

export const mockOrders: Order[] = [
  {
    id: 'order-1',
    orderNumber: 'ORD-2024-001',
    workerId: 'worker-1',
    workerName: 'Alex Chen',
    platform: 'platform_a',
    status: 'completed',
    amount: 450,
    createdAt: new Date(Date.now() - 2 * 3600000),
    completedAt: new Date(Date.now() - 1800000),
  },
  {
    id: 'order-2',
    orderNumber: 'ORD-2024-002',
    workerId: 'worker-1',
    workerName: 'Alex Chen',
    platform: 'platform_a',
    status: 'in_progress',
    amount: 350,
    createdAt: new Date(Date.now() - 1200000),
  },
  {
    id: 'order-3',
    orderNumber: 'ORD-2024-003',
    workerId: 'worker-2',
    workerName: 'Jordan Blake',
    platform: 'platform_b',
    status: 'pending',
    amount: 520,
    createdAt: new Date(Date.now() - 600000),
  },
  {
    id: 'order-4',
    orderNumber: 'ORD-2024-004',
    workerId: 'worker-3',
    workerName: 'Morgan Lee',
    platform: 'platform_c',
    status: 'in_progress',
    amount: 680,
    createdAt: new Date(Date.now() - 300000),
  },
  {
    id: 'order-5',
    orderNumber: 'ORD-2024-005',
    workerId: 'worker-6',
    workerName: 'Devon Park',
    platform: 'platform_c',
    status: 'completed',
    amount: 420,
    createdAt: new Date(Date.now() - 24 * 3600000),
    completedAt: new Date(Date.now() - 12 * 3600000),
  },
]

export const mockPayroll: PayrollEntry[] = [
  {
    id: 'payroll-1',
    workerId: 'worker-1',
    workerName: 'Alex Chen',
    period: '2024-03-01 to 2024-03-31',
    totalEarnings: 4520,
    totalDeductions: 452,
    netPay: 4068,
    ordersCompleted: 28,
    status: 'paid',
    createdAt: new Date('2024-04-05'),
  },
  {
    id: 'payroll-2',
    workerId: 'worker-2',
    workerName: 'Jordan Blake',
    period: '2024-03-01 to 2024-03-31',
    totalEarnings: 3210,
    totalDeductions: 321,
    netPay: 2889,
    ordersCompleted: 22,
    status: 'paid',
    createdAt: new Date('2024-04-05'),
  },
  {
    id: 'payroll-3',
    workerId: 'worker-3',
    workerName: 'Morgan Lee',
    period: '2024-03-01 to 2024-03-31',
    totalEarnings: 5890,
    totalDeductions: 589,
    netPay: 5301,
    ordersCompleted: 34,
    status: 'approved',
    createdAt: new Date('2024-04-05'),
  },
]

export const mockAlerts: Alert[] = [
  {
    id: 'alert-1',
    type: 'warning',
    title: 'High Error Rate Detected',
    message: 'Platform B has reported error rate of 8.5%',
    severity: 'high',
    timestamp: new Date(Date.now() - 30 * 60000),
    resolved: false,
  },
  {
    id: 'alert-2',
    type: 'error',
    title: 'Worker Offline',
    message: 'Worker W-005 (Taylor Kim) has been offline for 3+ hours',
    severity: 'medium',
    timestamp: new Date(Date.now() - 60 * 60000),
    workerId: 'worker-5',
    resolved: false,
  },
  {
    id: 'alert-3',
    type: 'info',
    title: 'New Worker Assignment',
    message: 'Worker W-004 assigned to high-priority batch',
    severity: 'low',
    timestamp: new Date(Date.now() - 2 * 3600000),
    resolved: true,
  },
]

export const mockDashboardMetrics: DashboardMetrics = {
  totalWorkers: 6,
  activeWorkers: 4,
  totalOrders: 47,
  ordersCompleted: 32,
  ordersInProgress: 12,
  totalEarnings: 21105,
  averageOrderValue: 449,
  systemHealth: 92,
  platformSummaries: [
    {
      platform: 'platform_a',
      activeWorkers: 2,
      totalOrders: 16,
      ordersCompleted: 12,
      ordersInProgress: 3,
      totalEarnings: 7210,
      errorRate: 2.1,
    },
    {
      platform: 'platform_b',
      activeWorkers: 1,
      totalOrders: 14,
      ordersCompleted: 10,
      ordersInProgress: 3,
      totalEarnings: 6340,
      errorRate: 8.5,
    },
    {
      platform: 'platform_c',
      activeWorkers: 2,
      totalOrders: 17,
      ordersCompleted: 10,
      ordersInProgress: 6,
      totalEarnings: 7555,
      errorRate: 3.2,
    },
  ],
  recentAlerts: mockAlerts,
}
